### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by tyilo** [lucaspiller/shortly#4]
Loading the page with Chrome 28.0.1500.6 dev, fails with the error:

```
Uncaught ReferenceError: $ is not defined
```

I think this is because you are using `async` in you `script` tags.

**Comment by tyilo** [comment]
I also get the same error about 50 % of the time I load the page in Firefox 20.0.0.

**Comment by gabrielvincent** [comment]
Same here on Chrome.
